### ISSUE TITLE
Are user contributions superseding inference as they should?

### ISSUE THREAD

**Issue by sdfb** [sdfb/sdfb#293] opened 2018-02-07 12:35 UTC
By my lights, relationships like this should've been appearing at 60% but this wasn't.
<img width="300" alt="screenshot" src="https://user-images.githubusercontent.com/6977267/35914665-1555321e-0bd2-11e8-8539-2c0a04f521c1.png">

**Comment by jrladd** [comment] 2018-02-13 03:14
This one looks good to me now; it's showing up at 60%. @sdfb did you make another update to it?

![screen shot 2018-02-12 at 9 13 15 pm](https://user-images.githubusercontent.com/6046784/36131863-a96ab616-1039-11e8-90a6-2410a322922b.png)

**Comment by sdfb** [comment] 2018-02-18 11:08
Yes, I added the "enemy" type as above

**Comment by sdfb** [comment] 2018-02-18 11:12
Now remembering past conversations about this - Is it maybe only an issue for past user contributions?

**Comment by jrladd** [comment] 2018-02-20 19:51
That's possible, the user contributions that took place *before* we implemented this new rule won't have their max_confidence updated properly.

**Comment by jrladd** [comment] 2018-10-17 15:28
I'm closing this one, as it looks to be working for new contributions, as intended.

**Closed by jrladd** 2018-10-17 15:28 UTC
Labels: JavaScript/Rails
